inc/block.h, src/cache.cc, src/dram_controller.cc, src/ooo_cpu.cc
Fix for instruction and data collision. 
Packets / MSHR now track is_instruction vs. is_data separately. A line can now be both data and code (e.g., under JIT scenario).
This enables an mshr entry to be able merge instruction and data requests, and forward them to both icache and dcache once resolved.
=> fixed instruction and data collision. removed old fix

src/main.cc
`O3_CPU::l1i_prefetcher_initialize()` is defined in each L1I prefetcher but called from nowhere, so add a function call.
=> Call the initializer of L1I prefetcher

README.md
The build script expects 7 arguments but the old README had only 6.
Added `L1I_PREFETCHER` to the list of arguments in doc.
=> Update README with build script arguments

src/main.cc, src/ooo_cpu.cc
The ROB.next_fetch member is never modified, so it always keeps its default value of zero. This causes the scheduler to always run from ROB.head to ROB.SIZE, which is a bug. This pull request changes it so that it runs from ROB.head to ROB.tail, still halting early if it reaches a scheduled instruction or the machine's schedule width. This results generally in an increased performance in the simulations.
=> Bugfix: Underutilized scheduling width

inc/block.h, inc/ooo_cpu.h, src/main.cc, src/ooo_cpu.cc
Now the entire scheduler width is more correctly and consistently used to find instructions ready to execute and/or issue loads.  Also, the loads associated with an instruction can no be issued before the instruction's register dependencies are freed up for some register access patterns.
=> Scheduler update

src/ooo_cpu.cc
```
uint32_t count_decodes = 0;
for(uint32_t i=0; i<DECODE_BUFFER.SIZE; i++)
{
... (decode an instruction) ...
count_decodes++;
if(count_decodes > DECODE_WIDTH) // DECODE_WIDTH is set to 6
{
break;
}
}
```
The above original code is executed as follows;
count_decodes = 0, 1, 2, 3, 4, 5, 6, then break.
so up to 7 instructions (more than DECODE_WIDTH) are decoded in one cycle.
It is correct to use `>=` instead of `>` as line 753.
=> Fix decode width

src/ooo_cpu.cc
I think decoder should be pipelined.
This pull request addresses this issue.
If it's intentionally non-pipelined, I think it should be noted somewhere.
=> Pipeline decoder

src/ooo_cpu.cc
Fetched instructions become unfetched (inflight) state when fetching another instruction that is in the same cache line is started.
This means that fetched instructions sometimes cannot be decoded, leading to performance degradation.
=> Fix a bug that fetched instructions become unfetched state

inc/block.h, inc/cache.h, prefetcher/ip_stride.l2c_pref, prefetcher/kpcp.l2c_pref, prefetcher/l1d_prefetcher.cc, prefetcher/l2c_prefetcher.cc, prefetcher/llc_prefetcher.cc, prefetcher/next_line.l1d_pref, prefetcher/next_line.l2c_pref, prefetcher/next_line.llc_pref, prefetcher/no.l1d_pref, prefetcher/no.l2c_pref, prefetcher/no.llc_pref, prefetcher/spp_dev.l2c_pref, prefetcher/va_ampm_lite.l2c_pref, prefetcher/va_ip_stride.l2c_pref, prefetcher/va_next_line.l1d_pref, src/cache.cc, src/ooo_cpu.cc
Added basic virtual address space data prefetching, along with example prefetchers.  This builds on the existing interface for data prefetchers, giving them the virtual address as well as the physical address.  A cache line can now be prefetched using its virtual address and the new function va_prefetch_line().  This allows you to prefetch outside of page boundaries, and gives visibility into which physical pages are contiguous in the virtual address space.
For this first version, VA->PA translation happens magically after a fixed number of cycles.
=> Virtual Address Space data prefetching

src/cache.cc, src/ooo_cpu.cc
The bug:- If an instruction prefetch request from L1I prefetcher is present in L2C and demand request comes from L1D for the same cache block, then fill_l1i information will be lost. If a subsequent instruction demand request comes to same cache block, it will get merged in L1I MSHR and it will wait forever. 
This will also not create a deadlock situation because deadlock is checked once the request reaches ROB.
=> MSHR merging:- Keep prior fill information

src/ooo_cpu.cc
In the previous version, there were many dependency inversions,
especially on A64 traces.
=> Fix RAW dependency calculation (#47)

src/ooo_cpu.cc
In two places, ooo_cpu.cc had a right shift by a literal 6. This commit changes that to LOG2_BLOCK_SIZE, which was the intent. This change prevents future errors where the block size may change, but these lines will be unchanged.
=> Removed magic numbers in instruction fetch

inc/ooo_cpu.h, src/ooo_cpu.cc
1) Merged RTE0 and RTE1 into a single buffer, called ready_to_execute.  NOTE: this new buffer is still just a simple FIFO, not a priority queue (yet ...).
2) Before, all instrs w/ loads would bypass the RTE queues, and would just get marked as executed when their loads resolved, ignoring the limits of the core's EXEC_WIDTH.  Now, all instructions must respect the EXEC_WIDTH before they can pass through the complete_execution() function.
=> Unified ready-to-execute queues; fixed bug where instrs w/ loads executed for free

inc/instruction.h, inc/ooo_cpu.h, src/ooo_cpu.cc
Programs, especially those with small instruction footprints, tend to access the same instruction cache line many times before moving on to another line. While the L1I does hold the cache line, it has a hit latency of 4 cycles. Once a demand returns from the L1I, all instructions in the ROB from that cache line are marked as fetched. However, this excludes instructions that enter the ROB just after their line returns. For these instructions, we must create a new demand.
This patch introduces an instruction buffer that keeps the most recent instruction block and marks an instruction in this block as immediately fetched if it is read from the trace. As submitted, this patch has only one entry, but is configurable in the number of sets and ways, managed in an LRU fashion.
My tests suggest …
=> Added L0 instruction buffer

src/main.cc
A simple change to main.cc to reset the prefetch statistics after warm up. Prior to this, the number of useful/useless prefetches could exceed the number of actual prefetch requests recorded during the simulation period.
=> Prefetch stats

inc/cache.h, inc/champsim.h, src/cache.cc, src/main.cc, src/ooo_cpu.cc
Cache write bandwidth can now be something other than 1 cache line per cycle.  It also makes it so that cache fill and write back operations both share the same limited resource, rather than each having their own dedicated, hard-coded 1/cycle.
In each cache, you can set MAX_WRITE, which does the same thing for fills and write backs that MAX_READ does for reads and prefetches.
Also, added a feature that automatically quits at the end of the trace for single core simulations, rather than wrapping back around to the beginning of the trace.  Multi-core simulations should be unaffected.
=> Cache write bandwidth

inc/champsim.h, inc/vmem.h, src/cache.cc, src/main.cc, src/ooo_cpu.cc, src/vmem.cc
This is the first step in implementing the ideas presented in Issue #49 
It replaces the va_to_pa() function with a new class, called VirtualMemory.  The VirtualMemory class has a function, va_to_pa(), which offers the same functionality as the old function, but is much simpler and faster, and will be easier to integrate with future virtual memory system changes like TLBs and page walkers.  The capacity, page size, and number of levels in the page table are all configurable.  It also uses its own random number function to shuffle the physical address space, so as to not interfere with any other RNG systems.
The new class also allows you to get the address of the page table entry for a given virtual address in each level of the page table.  This is the part of the code that I'm less sure …
=> Virtual Memory overhaul, part 1

src/ooo_cpu.cc
As I was making other changes, I noticed that the ITLB was receiving no requests, because instructions were entering the IFETCH_BUFFER magically translated. This change removes that magic in favor of actually using the TLB.
=> Removed magic in instruction VA translation

src/ooo_cpu.cc
Cleanup Fetch - the DIB lookup was happening in between seeing if the IFETCH_BUFFER instructions needed to be translated or fetched.  Now DIB lookup happens before checking to see if anything needs to be translated.  This will result in fewer unnecessary ITLB lookups.
Debug DIB - DIB set calculation was done with byte-address of instruction, rather than cache line address (>>6).  Also, instructions are now added to the DIB after they make it through the decode stage the first time, instead of immediately after they're fetched.
This still has the problem that once we add a cache line to the DIB that all instructions from that cache line will be magically fetched and decoded, including those we haven't actually seen yet.  I don't know how big of a problem that is, but this should still be a …
=> Implemented Decoupled Front End, plus cleanup Fetch, and fix a few bugs in Decoded Instruction Buffer

src/ooo_cpu.cc
This commit eliminates register dependencies until the warmup phase is complete.  This causes the warmup phase's IPC to be much higher, leading to faster warmup times.  Warmup phase IPC is already meaningless, so I imagine making it even more meaningless isn't a bad thing.  Branch predictors, cache replacement algorithms, cache contents, and prefetchers are all warmed up as normal.  The final reported IPC of the simulation phase, as well as all other reported metrics, should be very similar to they were before this commit, but not identical.
Please experiment with this and see how much it changes the metrics you care about.  If this doesn't harm anyone else's work, then it might as well be merged in, but it's not a huge deal either way.
=> Speed up warmup execution by ignoring register dependencies

branch/bimodal/bimodal.cc, branch/gshare/gshare.cc, branch/hashed_perceptron/hashed_perceptron.cc, branch/perceptron/perceptron.cc, btb/basic_btb/basic_btb.cc, champsim_config.json, config.sh, inc/ooo_cpu.h, src/main.cc, src/ooo_cpu.cc
This is not ready for prime time yet, but I wanted to get some eyeballs on it early as I'm expecting it to go through plenty of iteration.  I would appreciate help not only with code, style, and simulator architecture, but also branch target prediction architectures in general.  I'm a BTB novice.
This PR adds non-perfect BTBs to ChampSim.  How this fits in ChampSim is that the branch predictor is now expected to return either 0 for non-taken branches, or the specific byte address of the branch target for taken branches.  The branch predictor can get help coming up with the specific target address from the BTB.  Basically how I'm imagining this will work is that the first line of the branch predictor will call the BTB to get its target prediction, and then the branch predictor can decide …
=> Added support for user-defined BTBs, and provided a sample Basic BTB

src/main.cc
I found that 4-core simulation was crashing at initialization due to attempting to free memory not allocated when adding multiple CPU's to the CPU list in main. Reserving the space ahead of initialization seems to fix the problem for the mixes I tested. This PR doesn't address any deadlocks that may occur, just the initialization failure.
=> Fix for 4-core simulation crashing

README.md, tracer/champsim_tracer.cpp, tracer/make_tracer.sh, tracer/quick_make.sh
This updates the README to direct trace-users to change the tracer building script to point to the Pintool directory (#100). I've also addressed the namespace error brought up in (#50). This can probably be pushed directly into master since it doesn't directly affect ChampSim's functionality.
=> Small update to tracer and REAME

README.md
Newer PIN tool versions can be made use of, since 3.2 is dated. Using a newer PIN tool version is necessary when working on newer linux kernels.
=> Added note in README on ChampSim tracer & PIN tool compatibility

src/main.cc
This was fixed in the develop branch a while ago, but never made it to the master branch. This is a few line change to reset the prefetch statistics when the cache statistics are reset after the warmup period.
=> reset prefetch statistics after warm-up period

src/cache.cc, src/ooo_cpu.cc
In the cache hierarchy, the write queue was the only queue that could not check itself for duplicates when it was full. This patch allows it to do that. It has some effect on write-heavy programs, since some store instructions that stalled at the head of the ROB due to a full L1D write queue are now able to merge their stores.
Note: This technically violates in-order stores. However, since the L1D read queue checks the write queue for forwarding on insert, I think the conditions for this to be problematic are extremely narrow. If that is a concern, let me know.
=> Allowed CACHE::WQ to merge entries if the queue is full

champsim_config.json, config.sh, inc/cache.h, inc/ooo_cpu.h, src/main.cc
This patch moves the number of reads and writes per cycle into the constructor of the caches and adds support for changing them to the configuration file. Previously, these values were hard-coded in the constructor of the core model.
=> Added cache bandwidths to constructors

champsim_config.json, config.sh, inc/dram_controller.h
This patch moves six more DRAM configuration items to the config file.
In the future, I want to make these members of the `MEMORY_CONTROLLER` class, but leaving them as preprocessor defines will work for now.
=> Moved DRAM configuration to config file

config.sh
This patch adds module directories (prefetcher/*/, replacement/*/, branch/*/, btb/*/) to the preprocessor's header search path. Now when competitors submit code, they can send header files too.
This patch also adds support for C sources. I did that because it was simple and I'm pretty confident it doesn't break anything.
=> Added module directories to header search paths

config.sh
This patch allows module declarations in the configuration file to be paths, either absolute or relative to the root of the repository.
This will allow users to keep their modules under separate version control. This was previously only possible by symlinking the directory into `prefetcher/`, or other module directory.
=> Allowed module declarations to be path-like

src/cache.cc
This patch fixes a bug where the caches would not look for an invalid way before finding a victim.
This should not affect performance currently, because there are no instances in the current model where a line is invalidated. But, this bugfix prevents issues if in the future if we implement any form of coherence or exclusivity.
=> Fixed bug where caches would ignore invalid ways when finding victims

inc/util.h, src/cache.cc, src/vmem.cc
Gino brought this bug to my attention today. There was an instance in cache.cc where the upper bits were getting chopped because the bitmask was only 32 bits long. This patch addresses that issue and also fixes an instance in vmem.cc where it might have also been occurring.
=> Fixed widths of bitmasks

inc/block.h, inc/cache.h, inc/ptw.h, inc/util.h, src/cache.cc, src/ptw.cc
I had a conversation with Dr. Jimenez where he pointed out to me that the develop branch had a significant performance degradation for certain traces. I traced this back to the `std::list<>::sort()` function. It implements a merge sort. However, in the `CACHE::handle_fill()` function, we have a situation where the first element needs to be reordered to the last, and merge sort is not well-suited to handle this case.
I fixed the problem by changing the MSHRs in the caches to never hold invalid entries. When an MSHR is filled, it is removed from the head of the list. When a packet is returned, its MSHR is promoted to a point where it follows all earlier returns, but precedes outstanding requests. I suppose this is an insertion sort optimized for the case where only one item is unsorted. …
=> Improved performance of MSHR filling

config.sh
Resolves #44.
About 7 weeks from today, Ubuntu 16.04 will reach end of life. It will have been the last operating system for which GCC 5, which does not support C++17, is the default. With its passing, it is an appropriate time to update to the next major feature set of C++. Not to do this would be unnecessarily locking us out of the feature set.
=> Update to C++17

inc/block.h, inc/circular_buffer.hpp, inc/instruction.h, inc/ooo_cpu.h, src/main.cc, src/ooo_cpu.cc
This patch spells the demise of the `CORE_BUFFER` class.
I've been meaning to get around to this for a while now, but here it is. This patch converts the ROB to use the `circular_buffer` class, where it can use proper iterators and algorithms. The place where this is most evident is in the `O3_CPU::do_scheduling()` and `O3_CPU::add_load_queue()` functions, where dependency resolution is now a reverse iteration given a functor. This improves readability and actually gives some speed improvement in my tests.
=> Changed ROB to be a champsim::circular_buffer

config.sh
This fixes a minor bug in #128 where module directories might not be searched for dependencies, causing them to sometimes not be rebuilt.
=> Added module directories to make's search path

branch/bimodal/bimodal.cc
This is a simple patch compared to my other ones. This is a simple facelift to the bimodal branch predictor. It removes preprocessor directives and uses a map of cores to tables, rather than an array, which will be more future-proof.
=> Updates to bimodal branch predictor

README.md, branch/bimodal/bimodal.cc, branch/perceptron/perceptron.cc, prefetcher/ip_stride/ip_stride.cc, src/main.cc
This patch fixes a few minor bugs with the CLI:
- `--traces` would terminate getopt, but not fill traces list.
- `-w` and `-i` would not capture argument.
- Removed unused `-s` and `-b`.
=> Fixed bug with "--traces" option

branch/perceptron/perceptron.cc, config.sh
This fix resolves an issue where the stated configurations in the wiki didn't properly configure the simulator. It's just a small fix, I'm sure I'll clean it up later.
=> Hotfix for perceptron and base-level core arguments

src/ptw.cc
I found a bug resulting from a typo in the PTW model. The check for PSCL3 used the level for PSCL2, which resulted in PSCL2 basically never mattering.
=> Fixed bug in PSCL level matching

src/ooo_cpu.cc
This pull request is related to issue #211.
Right now there are unnecessary stalls in the fetch stage when a cache line is requested and other instructions (e.g., to the same address) are enqueued in the fetch queue. These later do not initiate cache line look up until the previous instructions move to decode. In summary it seems that cache pipelining (issuing one request per cycle) is not allowed.
As a consequence this pull request improves performance.
=> Allow pipelined ITLB and L1I cache

.github/workflows/buildcheck.yml, .github/workflows/main.yml
The `add-and-commit` action that we have been using to automatically format commands doesn't work when the remote branch is a fork. To accommodate this, I've removed the triggering condition for pull requests. Instead, it will run when the pull request is merged.
=> Remove lint trigger for pull requests.

src/ooo_cpu.cc
Right now only one access to ITLB and L1I are performed per cycle. However, the default config file indicates that the ITLB and the L1I have two read ports. This pull request, related to issue #213, resolves the issue.
=> Allow multi-ported ITLB and L1I cache

inc/instruction.h, src/ooo_cpu.cc
Right now all conditional branches are resolved at execution. However, at decode they obtain the target address and they should correct their previous prediction if the new information would change it.
For example, assume that the branch (direction) predictor says taken, but the BTB does not find a target. The prediction would be not taken. However the branch is taken. When computing the target address at decode, the misprediction can be resolved.
But it could also happen that the branch is actually not taken. In that case, the initial prediction would have been correct, but on decode, the prediction should be changed to incorrect (the direction predictor is the one it should be trusted in this case).
After the change, a hashed_perceptron predictor should offer better IPC. A bimodal, may …
=> Resolve conditional branches early and re-evaluate them at decode

src/ooo_cpu.cc
For some reason, some non-branch instructions have the branch_taken field set. They should reset it.
This does not affect performance now.
=> Reset taken for non-branch instructions

src/cache.cc
This patch removes a duplicate line copying cache data and fixes a bug where, if the replacement policy indicated that a fill should bypass, the packet would never be returned, causing deadlocks.
=> Fixed bug where bypassed packets would not return

inc/block.h, inc/cache.h, inc/dram_controller.h, inc/memory_class.h, inc/ooo_cpu.h, inc/ptw.h, src/cache.cc, src/dram_controller.cc, src/ooo_cpu.cc, src/ptw.cc
This patch passes `PACKET` objects by const reference to the producers and consumers. The previous way of passing them, by pointer, implies some strange things about ownership and modification. Passing by const reference makes the interface clearly designate that the queue allocation and the returning actions will not modify the passed packet.
=> Pass PACKETs by const reference to memory request producers and consumers

inc/cache.h, inc/memory_class.h, replacement/lru/lru.cc
LRU is the only replacement policy with first-class status, where its metadata was stored in the blocks themselves. This moves the metadata into a separate LRU structure, which should be more informative to new users.
=> Removed LRU's first-class status

config.sh, inc/block.h, inc/cache.h, inc/champsim.h, inc/dram_controller.h, inc/ooo_cpu.h, prefetcher/spp_dev/spp_dev.cc, prefetcher/spp_dev/spp_dev.h, src/cache.cc, src/ooo_cpu.cc, src/ptw.cc, src/vmem.cc
The C preprocessor is a very powerful tool, but it is dangerous. It bypasses the type-checking of the compiler and can obscure scopes. In my opinion, there are some good uses of the preprocessor (and we use one particularly in ChampSim's configuration step), but most are bad uses. This patch removes some bad uses:
- The `DP(x)` macro is replaced with `if constexpr (champsim::debug_print)`, requiring that they always compile.
- Numerous `#defines` defining constants replaced with typed `constexpr` values.
- Some vestigial compilation conditionals removed.
=> Removed some preprocessor compile controls

btb/basic_btb/basic_btb.cc, test/900-btb-bounds-check.cc
The BTB module had a sneaky bug. If:
- There is more than one core, and
- The BTB mispredicts a direct branch, and
- The IP was one less than a multiple of 1024, and
- The IP was not present in the BTB
Then, there would be a buffer overflow and a later prediction to some other core will segfault. This patch includes a test to demonstrate that the bug exists as well as a fix for that bug.
=> Fixed bug in basic_btb

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
This patch adds a template to GitHub Issues that frames an issue as a feature request. It also automatically applies labels to both bugs and feature requests.
=> Added Feature Request Issue Template

config/instantiation_file.py, inc/instruction.h, inc/ooo_cpu.h, src/ooo_cpu.cc, test/140-single-dib-lookup.cc, test/200-rob-scheduling.cc, test/300-retire-from-rob.cc, test/900-btb-bounds-check.cc, test/mocks.hpp
This patch fixes a bug where undefined behavior (and possibly a double-free fault) could be reached through the following process:
1. A fetch is issued for block X (1)
2. More instructions are added to the IFB, which include instructions in block X
3. The fetch for X (1) returns
4. A fetch is issued for block X (2)
5. The two fetches do not get merged because the merging does not look in the CacheBus::PROCESSED queue.
6. The dependents on X (1) get marked as completed and promoted to decode
7. The dependents on X (1) get decoded and added to the DIB
8. The dependents on X (2) check the DIB (again), find a match, and get marked as both fetched and decoded
9. The dependents on X (2) promote out of the IFB
10. The fetch for X (2) returns
After this patch, the instruction contains a flag …
=> Fixed bug in DIB check

.github/workflows/buildcheck.yml, README.md
Resolves #275.
Texas A&M no longer allowed us to host the traces on their servers. Stony Brook University has generously offered to host them instead. This patch fixes the broken link.
=> Fixed broken DPC3 link

src/cache.cc
Resolves #268 
Somewhere along the line, it looks like the evicted address stopped being sent to the replacement policy. This patch resolves that bug. This bug highlights to me that it is important to test the module interfaces. However, it's not immediately clear to me how we can mock the interfaces for proper testing. I'll look for an idea and either submit it as a different patch or part of this one. Until we can test this change, I'm inclined to let it sit.
=> Fixed bug sending evicted address to replacement policy on fill

src/cache.cc, test/421-prefetch-fill-level.cc
When a prefetch is issue with `fill_this_level == true`, the prefetch request never fill the lower level. This patch fix the bug, and add two test to verify the behavior.
The flag `fill_this_level` packet flag is never set to true
After the first MSHR miss, the `fill_this_level` flag is set to true.
https://github.com/agusnt/ChampSim/blob/90c9e5b09f39c146c3cda872a7b8ad8cb0111776/src/cache.cc#L208-L211
=> Fix upper level prefetch

LICENSE, config.sh, inc/block.h, inc/cache.h, inc/champsim.h, inc/circular_buffer.hpp, inc/delay_queue.hpp, inc/dram_controller.h, inc/instruction.h, inc/memory_class.h, inc/ooo_cpu.h, inc/operable.h, inc/ptw.h, inc/trace_instruction.h, inc/tracereader.h, inc/util.h, inc/vmem.h, src/cache.cc, src/dram_controller.cc, src/main.cc, src/ooo_cpu.cc, src/ptw.cc, src/tracereader.cc, src/vmem.cc, tracer/cvp_converter/cvp2champsim.cc, tracer/pin/champsim_tracer.cpp
On January 1, the license of ChampSim will be changed from GPLv3 to Apache 2.0.
The primary difference following this change is a clarification that user module code and derived hardware designs should not be considered to be bound under the attribution terms of the license.
=> Updated License

.github/workflows/test.yml, inc/tracereader.h, src/tracereader.cc
This patch changes how the trace file pointer is instantiated on Mac devices and the file is read. I've confirmed it works on M1's.
=> Added support for Apple devices

btb/basic_btb/basic_btb.cc, test/cpp/src/165-basic-btb-no-evict-on-unknown-target.cc, test/cpp/src/166-issue296-basic-btb-no-mispredict-on-not-taken.cc
This is a necessary fix after the last patch on the BTB. I believe it is not good to use the BTB to predict conditional branches, so always taken info is now only for inconditional branches.
=> Always taken not used for conditional branches

inc/repeatable.h, inc/tracereader.h, inc/util/detect.h, src/champsim.cc, src/main.cc, src/tracereader.cc, test/cpp/src/084-tracereader-eof.cc
Resolves #337.
This patch adds a run-to-end feature to ChampSim. If the user does not specify `-i` on the command line, the simulation will run to the end of the trace, then stop. If the user supplies `-i`, the behavior of the simulator is unchanged.
=> Stop simulation if the end of the trace is reached

config/modules.py, inc/cache.h, prefetcher/ip_stride/ip_stride.cc, prefetcher/next_line_instr/next_line.cc, prefetcher/no/no.cc, prefetcher/no_instr/no.cc, prefetcher/spp_dev/spp_dev.cc, prefetcher/va_ampm_lite/va_ampm_lite.cc, src/cache.cc, test/cpp/modules/prefetcher/address_collector/address_collector.cc, test/cpp/modules/prefetcher/metadata_collector/metadata_collector.cc, test/cpp/modules/prefetcher/metadata_emitter/metatadata_emitter.cc, test/cpp/modules/prefetcher/prefetch_hit_collector/prefetch_hit_collector.cc, test/cpp/src/420-issue-prefetch.cc, test/cpp/src/pref_interface.h
Resolves #344 
This patch adds a parameter to the prefetcher cache_operate hook that indicates whether the hit block was a prefetch or not. This will help prefetchers get good feedback on their performance, and it also allows easier migration from the IPC-1 prefetchers. This is, however, a breaking change for all existing code in the name of bringing instruction prefetchers and data prefetchers together.
=> Added useful_prefetch parameter to prefetchers

config/instantiation_file.py, config/parse.py, inc/cache.h, inc/channel.h, inc/defaults.hpp, inc/util/bits.h, replacement/drrip/drrip.cc, replacement/lru/lru.cc, replacement/ship/ship.cc, src/cache.cc, src/channel.cc, src/json_printer.cc, src/ooo_cpu.cc, src/plain_printer.cc, src/ptw.cc, test/cpp/modules/replacement/lru_collect/lru.cc, test/cpp/src/401-hit-latency.cc, test/cpp/src/402-miss-latency.cc, test/cpp/src/404-fill-bandwidth.cc, test/cpp/src/405-fill-eviction.cc, test/cpp/src/406-mshr-merge.cc, test/cpp/src/423-prefetcher-activate.cc, test/cpp/src/425-useless-prefetch.cc, test/cpp/src/431-merge-prefetch.cc, test/cpp/src/441-replacement-bypass.cc, test/cpp/src/442-replacement-interface.cc, test/cpp/src/repl_interface.h, test/python/test_parse.py
Resolves #338.
This patch makes the `access_type` enum a strong type. This will break some user code that respects the types passed to prefetcher and replacement hooks, but it means that illegal values passed to `"prefetch_activate"` in the configuration file result in a compile error, rather than failing silently.
=> Make unknown prefetch_activate values a compile-time error

btb/basic_btb/basic_btb.cc, inc/instruction.h, src/ooo_cpu.cc
This pull request includes two fixes:
The first one is that BRANCH_OTHER considered conditional branches in ChampSim. Among other effects, the most important current "bug" is that the BTB considers them as "always_taken" which is not right.
The second ones is considering that conditional branches can also read from other registers, and not just from flag registers.
In general, I think we should avoid to have a BRANCH_OTHER type as it may be confusing. But for now, this patch fixes some current problems.
=> BRANCH_OTHER are considered conditional.

src/cache.cc, test/cpp/src/402-miss-latency.cc
Fixed cache miss count in case of an MSHR full. The miss should only be counted once rather than in every cycle until an MSHR becomes available.
=> Avoid counting multiple misses with MSHR full

inc/util/algorithm.h, src/cache.cc, src/channel.cc, test/cpp/src/045-transform-while-n.cc
Fixes #359.
There was a bug in the tag lookup where cascading misses in the PTW might cause the L1D to deadlock. This patch allows the `inflight_tag_check` member to drain to the `translation_stash`, allowing bandwidth for translated packets (from the PTW) to be looked up.
=> fix: Resolved tag congestion

inc/cache.h, src/cache.cc, src/ooo_cpu.cc, src/vmem.cc
This patch fixes a bug where a MSHR merge in the TLB would discard the translation, resulting in occasionally failed `packet.address != 0` assertions.
=> Fixed bug where TLB MSHR merging would lose data

src/cache.cc, test/cpp/src/402-miss-latency.cc
This patch fixes a bug where the average miss time was calculated with the hits in the denominator, not the misses. This probably caused some confusion in what the numbers actually meant. This bug affected both the output to stdout and the JSON output.
=> Fixed bug where the wrong stats were used to calculate AMAT

.github/workflows/docs.yml, docs/Makefile, docs/README.txt, docs/_templates/versioning.html, docs/_templates/versions.html, docs/conf.py, docs/make.bat, docs/src/Creating-a-configuration-file.rst, docs/src/Modules.rst, docs/src/index.rst
This patch regards my recent comment on #12.
The wiki has not lived up to expectations for documentation. The wiki is only editable by maintainers and cannot be merged alongside the code that it describes.
This patch uses Sphinx and GitHub Pages to host the documentation instead. Each branch gets its documentation copied to the `gh-pages` branch, where it is read by Pages.
=> Migrated documentation into docs directory

src/cache.cc, test/cpp/src/407-writeback-dirty.cc
Cache-lines could potentially have their dirty flag reset if a read-like access was made before write-back/eviction.
Along with this, a test was created to ensure proper cache write-back for lines that should be marked dirty.
=> Fixed bug with cache line dirty flag being reset.

config/instantiation_file.py, config/util.py, test/python/test_instantiation_file.py, test/python/test_util.py
Fixed a bug where the queue sizes between cache levels was always the value of the LLC's queue sizes.
Reproducing the bug: Changing the L2's rq_size to 128 still resulted in it being set to 32 in the channel instantiation in .csconfig/[BUILD#]/inc/core_inst.inc. Also in core_inst.inc, without modifying the configuration file, the channels between each cache all had the same values despite differences in the default config file.
=> Fix: Varying queue sizes now varies queue sizes

inc/util/units.h, test/cpp/src/031-address-slice.cc
Build fails when GCC/Clang attempts to convert an initializer list to the proper return type.
Making these constructor calls explicitly defined fixes the issue.
=> fix: explicit constructor calls for units types

PUBLICATIONS_USING_CHAMPSIM.bib, README.md, docs/README.txt, docs/conf.py, docs/requirements.txt, docs/src/Publications-using-champsim.rst, docs/src/index.rst
This patch adds a page to the documentation to feature publications that use ChampSim.
Publications are sorted by year, with the newest first.
Authors can add their publication to the list by modifying `PUBLICATIONS_USING_CHAMPSIM.bib`. I'm not so certain about the name of this file. If anyone has suggestions, I'd be open to a better name.
=> Added 'Publications' page to documentation

src/ooo_cpu.cc
In the current implementation of promote_to_decode(), available_fetch_bandwidth does not account for the remaining space in the DIB_HIT_BUFFER and DECODE_BUFFER. As a result, the number of entries in these buffers can exceed their sizes. I have modified the bandwidth so it will consider the available space before promote them to decode.
=> bug fixed: entries of DIB hit buffer and decode buffer exceed the limits

champsim_config.json, config/parse.py, inc/dram_controller.h, src/dram_controller.cc, test/cpp/src/702-dram-refresh.cc
With a release coming up, I would like to make a final tweak to the dram.
Default config numbers are updated and taken from real DDR5 at the 3200MHz frequency and at the config's density.
Refresh period has been reduced in half to 32ms, as this is standard for DDR5.
These newer updates revealed an issue with the timings as they stood. tRAS * rows_to_refresh should approximate the refresh delay somewhat better than previously. Previously I was doing (tRP + tRAS) * rows_to_refresh, but this is very conservative in terms of timing (20-30% too high). This doesn't become an issue until we start refreshing more often like in DDR5, and then it is very noticeable.
From what I can tell, tRFC (time after a refresh is issued before a bank can be used again) does not follow a strict tRAS + tRP …
=> Update champsim_config.json to reflect low-grade DDR5 memory, fix timing issue with refresh

prefetcher/va_ampm_lite/va_ampm_lite.cc, prefetcher/va_ampm_lite/va_ampm_lite.h, test/cpp/src/453-va-ampm-lite-behavior.cc
AMPM simulation performance is currently awful. It is nearly impossible to run simulations with it, and many simulations simply stop after a short period of time without a deadlock notification. IPC speedup seems incredibly good for certain traces, but those traces quickly livelock.
This is an attempted fix for what is causing this.
I have replaced the region-lru system with an lru-table with 128 ways. I don't believe I have modified anything else about the prefetcher besides this.
The resulting simulation time is much shorter, 50x+ faster for gcc-2226B.
However, it is currently failing the AMPM test.
I would appreciate a second set of eyes on this code to help identify why this behavior is different than the previous one, outside of different eviction policy.
Another note:
With this …
=> Attempt to Fix AMPM Performance

src/ooo_cpu.cc, test/cpp/src/200-rob-scheduling.cc
I moved the producers_at(reg) search and erase from do_complete_execution to retire_rob.
This necessitated another check in the scheduler.
ie. if the instruction is still in the list, but
has completed, don't depend on it since it's ready.
=> Fix for issue #527. Reg producers erase moved to retire

config/instantiation_file.py, inc/cache_stats.h, src/cache.cc, src/json_printer.cc, src/plain_printer.cc, test/cpp/src/402-miss-latency.cc, test/cpp/src/425-useless-prefetch.cc, test/cpp/src/431-merge-prefetch.cc, test/cpp/src/498-cache-plain-printer.cc
Three things this pr covers:
1. Added downstream stats to the cache. This shows how many of each type of packet went downstream from said cache. This should always be <= misses, but does not count misses that hit in the mshr. It should match up with accesses to the downstream cache/dram.
2. Cache miss latency is now calculated as the total time each MSHR was open divided by the number of downstream packets (excluding writes) from that cache. If a demand merges into a prefetch, then right now it updates the open time to the demand. I am not sure if this should be done or not. I can imagine that many prefetches never get a demand merge, so this change doesn't seem too meaningful, unless we only count demands when calculating the miss latency.
3. instantiation_file.py had a bug where …
=> Added downstream stats for cache, fixed cache miss latency calculations to use downstream.

branch/hashed_perceptron/folded_shift_register.h, branch/hashed_perceptron/hashed_perceptron.cc, branch/hashed_perceptron/hashed_perceptron.h, inc/util/bit_enum.h, test/cpp/src/174-hashed-perceptron-ghist.cc
Somewhere along the develop history, I think I broke the hashed perceptron predictor. I believe this patch fixes that problem. I refactored the global history into its own class that folds a shift register. This class is probably worth looking at as an eventual candidate to promote to the MSL. I think it could have good general usage.
The new tests cover the global history, since that's where the bug was, but there still are no tests covering the perceptron behavior. Testing that would require the perceptron to be factored out into a testable unit. If it continues to be broken, I'll look into that.
=> Fixed Hashed Perceptron predictor

btb/basic_btb/return_stack.cc
When running some of our cvp traces, we would get errors since the virtual addresses were too large to use a signed offset.
Since we just want the absolute value, I inserted a ternary operator here to call uoffset(x,y) if x < y and uoffset(y,x) if x > y.
The actual differences between the two are very small, it's just that the inputs were incredibly large.
=> fixed btb return stack for large virtual addresses

inc/cache_stats.h, inc/event_counter.h, src/cache.cc, src/plain_printer.cc, test/cpp/src/498-cache-plain-printer.cc
There have been questions about what the cache stats from the plain printer are indicating for multi-core runs.
This change indicates the origin core that the cache stats are being split by. The json files already do this, but the plain printer does not, so this brings it into sync.
=> Changed plain-printer to indicate origin cpu of cache stats.

inc/dram_controller.h, src/dram_controller.cc, test/cpp/src/701-dram-scheduler.cc, test/cpp/src/751-channel-bit-select.cc
Modernized dram mappings have been added to the memory controller.
Because our model allows for arbitrary values for # of rows,banks, etc..., we cannot directly copy mappings from real machines.
This mapping is heavily based on the re'd zen4 mappings.
Each channel bit is xor'd with all row bits.
Bankgroup and bank bits are xor'd all at once, as follows.
[bank bits][bank group bits]
^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^
[row bits [bg bits + bk_bits:0]]
^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^
[row bits [(bg_bits + bk_bits)*(i+1)][(bg_bits + bk_bits)*i]]
....
....
Until we are out of row bits to xor with.
New tests were added to test this, and ensure that no aliasing occurs in these mappings.
=> Added modern dram mappings to memory controller.

README.md
the `--warmup_instructions` and `--simulation_instructions` options were deprecated, changed for the "-" version in the README
=> fix: deprecated options in README example

Makefile, test/cpp/src/044-extract.cc
I had to update vcpkg to get a dependency I want for my fork. I hope this change to bump the version is also useful for upstream too.
Bumps [vcpkg](https://github.com/Microsoft/vcpkg) from `69efe9c` to `1de2026`.
- [Release notes](https://github.com/Microsoft/vcpkg/releases)
- [Commits](https://github.com/microsoft/vcpkg/compare/69efe9cc2df0015f0bb2d37d55acde4a75c9a25b...1de2026f28ead93ff1773e6e680387643e914ea1)
The new revision is the last vcpkg release that is not affected by:
https://github.com/fmtlib/fmt/issues/4133
=> Bump vcpkg from 69efe9c to 1de2026

src/cache.cc, src/ooo_cpu.cc
The formatter of champsim::address does not recognize any format specification. Remove such format specifications.
=> Fix champsim::address formats in debug prints

src/ptw.cc
The semantics of is_last_step is inverted so correct it. There is no behavioral change as callers of the function were based on the inverted semantics, which are corrected too.
=> Fix is_last_step in PageTableWalker::finish_packet

src/ooo_cpu.cc, test/cpp/src/200-rob-scheduling.cc
O3_CPU::schedule_instruction() accidentally copies RegisterAllocator. Use a reference to avoid this copy. This change gives 7x speedup.
=> ooo_cpu: Do not copy RegisterAllocator

src/champsim.cc
The current livelock duration is too short. This can result in significant stall-drain behavior in some traces triggering the livelock. As a resolution, we can extend the livelock period which should help prevent these false positives at the expense of potentially spending longer livelocked. Champsim can chew through 10M cycles like nothing, so I don't think this will be an issue.
This is causing problems for ECEN 676 at the university, so I would appreciate this PR having high prio.
=> Update champsim.cc to extend livelock period from 100K cycles to 10M cycles

src/ptw.cc, test/cpp/src/600-ptw-path.cc, test/cpp/src/603-pte-page-correctness.cc
Fixes a bug that causes PTW walks that were previously cached to begin at 1 level lower than expected.
I am still not entirely sure whether this is a bug or not.
Since VMEM has to allocate more pages for the page tables after this fix, I would assume this was indeed a bug. If it wasn't, those page table pages would have been allocated originally.
However, this also means that the top-level of the PSCL doesn't seem to reduce the number of translations required when it hits.
Essentially what is happening is that each level of the PSCL should cache entries from its respective level of the page table hierarchy.
Level 5 (top) should cache entries in the level 5 table, level 4 should cache level 4 entries, and so on.
We don't have a level 1 table, since this is the actual translation.
When we …
=> PTW PSCL Fix

Makefile, config/makefile.py
The dependencies of the main file in a build not for testing was not checked, which could result in an invalid build when one of the dependencies like inc/channel.h was modified. Check them properly by including dependency rules of the build specified in _configuration.mk.
=> Check dependencies of the main file

.github/workflows/test.yml
Ubuntu 20.04 on GitHub Actions became fully unsupported by 2025-04-15.
=> Stop testing on Ubuntu 20.04 on GitHub Actions
